"""create_incident_logs_table

Revision ID: 9ba067d09d1c
Revises: 
Create Date: 2026-06-27 13:58:23.953806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 

# revision identifiers, used by Alembic.
revision: str = '9ba067d09d1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_logs',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('ml_integrated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    # Kept the standard indexes, removed the duplicate geom indexes
    op.create_index(op.f('ix_incident_logs_incident_id'), 'incident_logs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_logs_is_verified'), 'incident_logs', ['is_verified'], unique=False)
    op.create_index(op.f('ix_incident_logs_user_id'), 'incident_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_logs_user_id'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_is_verified'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_incident_id'), table_name='incident_logs')
    op.drop_table('incident_logs')
    # ### end Alembic commands ###